### ISSUE TITLE
0.4.0: Could not find module initializers/ember-engines-router-service

### ISSUE THREAD

**Issue by kpfefferle** [villander/ember-engines-router-service#67] opened 2022-06-08 16:23 UTC
When attempting to use v0.4.0 of this addon, the tests we have in our application that use the engine containing this addon blow up with the following error:

```
Error: Could not find module `[EMBER_ENGINE]/initializers/ember-engines-router-service` imported from `(require)`
```

v0.3.0 continues to work as expected. I'm guessing this is something related to the migration to v2 addon format? We are using ember-auto-import v2 so v2 addons should theoretically work 🤔

**Comment by villander** [comment] 2022-06-08 16:27
Hey, @kpfefferle is this error only happening in the test environment? Could you please provide a minimal reproduction then I can help more 😄 since we didn't those issues in our tests with the dummy app

**Comment by kpfefferle** [comment] 2022-06-09 18:19
@villander We get the same error at runtime in local development when trying to access any route that uses the engine, so this is not an issue isolated to the test environment.

I'll try and poke at this further later today.

**Comment by anehx** [comment] 2022-08-26 09:37
I'm having the exact same issue here: https://github.com/projectcaluma/ember-caluma/pull/2001

**Comment by SergeAstapov** [comment] 2022-09-20 04:26
the root cause of the problem I believe is that initializer file `dist/_app_/initializers/ember-engines-router-service.js` published to NPM has following contents:

```js
export { default } from "ember-engines-router-service/initializers/ember-engines-router-service.js";
```

and it should be

```js
export { default } from "ember-engines-router-service/initializers/ember-engines-router-service";
```

The simplest solution I see - bump `@embroider/addon-dev` package and release 4.0.1 with the new tarball.

now trying this in our app to confirm this is 1. the actual root cause and 2. proposed change makes the trick

**Comment by SergeAstapov** [comment] 2022-09-20 19:09
@kpfefferle @anehx @villander FYI made a PR #73

EDIT: I may be wrong about the root cause, keep looking...

**Comment by anehx** [comment] 2022-09-21 06:57
@SergeAstapov I just checked out your branch and used that build for my use case. Sadly, it didn't work..

However, if I put `console.log("something")` above or below the `export { default } from ...` in `dist/_app_/initializers/ember-engines-router-service.js` everything works as expected. I have no idea why..

I also tried replacing the content of the initializer reexport to
```js
import initializer from "ember-engines-router-service/initializers/ember-engines-router-service";
export default initializer
```
which doesn't change the meaning of the code but it worked.

I hope that helps..

**Comment by SergeAstapov** [comment] 2022-10-07 01:44
@kpfefferle @anehx would you mind to share how dependency tree looks like in your case and if you use Embroider for the app build or "classic" Ember CLI?

there was a discussion on Discord which has similar symptom https://discordapp.com/channels/480462759797063690/568935504288940056/1027599076709126194

**Comment by anehx** [comment] 2022-10-07 11:43
@SergeAstapov I'm not exactly sure what you mean by dependency tree - what output should I paste? Also, I'm using classic ember without embroider. Since a minimal reproduction might help more than outputs from my specific use case I created one here: https://github.com/anehx/ember-engines-router-service-reproduction, also I added a branch that uses embroider instead of classic ember (it didn't produce the error!): https://github.com/anehx/ember-engines-router-service-reproduction/tree/embroider

Hope this helps!

Edit: I read the discussion you linked, there seems to be a workaround [by adding this package to the dev dependencies of the application](https://github.com/anehx/ember-engines-router-service-reproduction/commit/ec9cd18b2badd233ddb0dd674cb50cddbfa6e096), but I don't think this can be the solution to this. Wouldn't this even override the built in ember router service?

**Comment by SergeAstapov** [comment] 2022-10-07 12:16
@anehx thank you! Reproduction is always the best!

**Comment by kpfefferle** [comment] 2022-10-11 15:51
@SergeAstapov Our application is also using "classic" ember-cli, not Embroider 👍

**Comment by LucasPadovanPeek** [comment] 2022-10-26 13:47
Hello!
We are getting a similar issue while trying to use the router
![image](https://user-images.githubusercontent.com/108287353/198039810-6704a18e-f47e-4eeb-a427-3e1de59998ab.png)

![image](https://user-images.githubusercontent.com/108287353/198039910-df1dfdc3-f684-44b8-8297-e540f83f1471.png)

It seems that for engines the initializer is not being found, or it is not correctly setup or the files are not exported to the correct path.

**Comment by SergeAstapov** [comment] 2022-10-27 02:18
got some updates here:
there is nothing wrong with `ember-engines-router-service` package itself.

The issue is: any v2 addon in the engine does not get pulled into build.
the reason I didn't see it in our app - we (somehow) had added  `ember-engines-router-service` to `devDependencies` in the host app and it gets pulled into build.

> Wouldn't this even override the built in ember router service?

@anehx it will be inert in the host app thanks to this check https://github.com/villander/ember-engines-router-service/blob/master/addon/src/-private/engine-ext.js#L8

**NOTE:**
temporary solution for this issue until it gets fixed in `ember-auto-import` - add `ember-engines-router-service` to `devDependencies` of the host app.

**Comment by anehx** [comment] 2022-10-28 13:31
@SergeAstapov Thanks for analyzing this issue! Is there an issue for `ember-auto-import` I could track?

For now, we will stay away from the rather hacky workaround and stay on `v0.3.0` since `v0.4.0` does not really bring any enhancement.

**Comment by SergeAstapov** [comment] 2022-10-28 14:26
@anehx I wonder if https://github.com/ef4/ember-auto-import/pull/512 will fix  the issue, but it's blocked with https://github.com/ember-engines/ember-engines/pull/820

> For now, we will stay away from the rather hacky workaround and stay on v0.3.0 since v0.4.0 does not really bring any enhancement.

from functional perspective, v0.3.0 and v0.4.0 are same. the main and only difference is v2 addon format in the latter version

**Comment by villander** [comment] 2022-10-28 16:46
Thanks for figuring it out @SergeAstapov let's wait for these fixes and see how it goes. 🤞

**Comment by RobbieTheWagner** [comment] 2023-06-15 19:29
I'm unsure if the error we are getting is related to this or not, but after updating to Ember 3.28, the router service is the app one. I am guessing the initializer is not running.

**Comment by villander** [comment] 2024-02-19 21:49
@SergeAstapov any news here regarding your last comment?

**Comment by SergeAstapov** [comment] 2024-03-04 16:05
@villander unfortunately I don't have any updates on this issue. Haven't been able to find root cause in `ember-auto-import` and seen similar issues in our internal v2 addons as well for services re-exports only.

**Comment by villander** [comment] 2024-03-14 17:25
@RobbieTheWagner could you please create a minimal reproduction with this issue?

**Closed as completed** 2024-04-27 18:29 UTC
